### ISSUE TITLE
Add functions to set default Size/Rating etc

### ISSUE THREAD

**Issue by ryanhalliday** [ry167/twig-gravatar#2]
This will remove the need for massive filter chains

**Comment by robertfausk** [comment]
Proposal:

```
<?php

class TwigGravatar extends \Twig_Extension {

    public function __construct($useHttps = null, $default = null, $size = null)
    {
        $this->default = $default;
        $this->useHttps = $useHttps;
        $this->size = $size;
    }
```
and you can wire the config like this:
```
    twig.extension.gravatar:
        class: \TwigGravatar
        arguments:
            $default: 'monsterid'
            $useHttps: true
            $size: 24
        tags:
            - { name: twig.extension }
```
or simply use defaults but https:
```
    twig.extension.gravatar:
        class: \TwigGravatar
        arguments:
            $useHttps: true
        tags:
            - { name: twig.extension }
```
![image](https://user-images.githubusercontent.com/1651297/38296513-d4b1e120-37f1-11e8-987f-863cfa237503.png)

WDYT? If you confirm with this approach, I will send a PR without BC.

PS: A PR with BC would use $useHttps=true as default value. Cause its more common now than in 2015.
